name: socialspark_app
description: "A new Flutter project using Clean Architecture."
publish_to: 'none' # Remove if you plan to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.0
  get_it: ^7.6.7
  flutter_bloc: ^9.0.0
  video_player: ^2.9.1
  chewie: ^1.7.5
  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  # State management
  provider: ^6.1.2

  # Networking
  http: ^1.2.2

  # Local storage (token, user session)
  shared_preferences: ^2.3.2

  # Functional programming helpers (for Either, Failure, etc. in clean arch)
  dartz: ^0.10.1

  # Form validation
  form_field_validator: ^1.1.0

  # Logging
  logger: ^2.4.0

  # ==== Scheduling & Sharing (added) ====
  path_provider: ^2.1.2
  share_plus: ^9.0.0
  flutter_local_notifications: ^17.1.2
  workmanager: ^0.9.0+3
  timezone: ^0.9.3
  url_launcher: ^6.3.2
  dio: ^5.9.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  equatable: ^2.0.5
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700